baseURL = "http://docs.influxdata.com/"
languageCode = "en-us"
title = "InfluxDB Documentation"

# Git history information for lastMod-type functionality
enableGitInfo = true

# Syntax Highlighting
pygmentsCodefences = true
pygmentsUseClasses = true

[menu]
  [[menu.versions]]
    name = "v1.x"
    url = "https://docs.influxdata.com"

[blackfriday]
  hrefTargetBlank = true
