baseURL = "https://v2.docs.influxdata.com/"
languageCode = "en-us"
title = "InfluxDB Documentation"

# Git history information for lastMod-type functionality
enableGitInfo = true

# Syntax Highlighting
pygmentsCodefences = true
pygmentsUseClasses = true

# Preserve case in article tags
preserveTaxonomyNames = true

# Markdown rendering options
[blackfriday]
hrefTargetBlank = true
smartDashes = false

# Menu items without actual pages
[menu]
  [[menu.versions]]
    name = "v1.x"
    url = "https://docs.influxdata.com"

[taxonomies]
  "v2.0/tag" = "v2.0/tags"
